# File Purpose: This file contains configuration settings for the Supabase backend, controlling how the database and services are set up.
# Last updated: 2025-05-21

[functions.process-submission]
enabled = true
verify_jwt = true
import_map = "./functions/process-submission/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-submission/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-submission/*.html" ]
